
package com.soprabanking.amplitude.createcustomer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "createCustomer", targetNamespace = "http://soprabanking.com/amplitude", wsdlLocation = "file:/data/git/mobiLoan/smg-connectors/src/main/resources/wsdl/createCustomer.wsdl")
public class CreateCustomer
    extends Service
{

    private final static URL CREATECUSTOMER_WSDL_LOCATION;
    private final static WebServiceException CREATECUSTOMER_EXCEPTION;
    private final static QName CREATECUSTOMER_QNAME = new QName("http://soprabanking.com/amplitude", "createCustomer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/createCustomer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREATECUSTOMER_WSDL_LOCATION = url;
        CREATECUSTOMER_EXCEPTION = e;
    }

    public CreateCustomer() {
        super(__getWsdlLocation(), CREATECUSTOMER_QNAME);
    }

    public CreateCustomer(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREATECUSTOMER_QNAME, features);
    }

    public CreateCustomer(URL wsdlLocation) {
        super(wsdlLocation, CREATECUSTOMER_QNAME);
    }

    public CreateCustomer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREATECUSTOMER_QNAME, features);
    }

    public CreateCustomer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateCustomer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreateCustomerPortType
     */
    @WebEndpoint(name = "createCustomerPortType")
    public CreateCustomerPortType getCreateCustomerPortType() {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "createCustomerPortType"), CreateCustomerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateCustomerPortType
     */
    @WebEndpoint(name = "createCustomerPortType")
    public CreateCustomerPortType getCreateCustomerPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "createCustomerPortType"), CreateCustomerPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREATECUSTOMER_EXCEPTION!= null) {
            throw CREATECUSTOMER_EXCEPTION;
        }
        return CREATECUSTOMER_WSDL_LOCATION;
    }

}
